#!/bin/sh
set -x
d="`dirname "$0"`"
echo $d
d="`cd "$d" && pwd`"
echo $d
bin="$HOME/bin"
for i in *.rb; do
	ln -s "$d/$i" "$bin/`basename "$i" .rb`"
done
for i in *.sh; do
	ln -s "$d/$i" "$bin/`basename "$i" .sh`"
done
